include:
    - path: "https://cnb.cool/netcat1/ci-templates/-/blob/main/template.yml"
      ignoreError: true

main: # 定义触发分支
  push: # 定义触发事件
    - stages: 
        - env:
            github_url: 404
          name: sync to github
          image: tencentcom/git-sync
          imports: https://cnb.cool/netcat1/secret/-/blob/main/envs.yml
          settings:
              target_url: ${github_url}
              auth_type: https
              username: ${GITHUB_USER}
              password: ${GITHUB_TOKEN}
        