include:
    - path: "https://cnb.cool/netcat1/ci-templates/-/blob/main/template.yml"
      ignoreError: true

main: # 定义触发分支
  push: # 定义触发事件
    env:
      github_url: 404
    stages: !reference [.sync-github]

          
        